/*
EmaoPay API

EmaoPay API.

API version: 1.0
Contact: support@emaopay.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emaopaysdk

import (
	"encoding/json"
)

// checks if the EmaopayMonitorMessageParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmaopayMonitorMessageParams{}

// EmaopayMonitorMessageParams struct for EmaopayMonitorMessageParams
type EmaopayMonitorMessageParams struct {
	Content *string `json:"content,omitempty"`
	PackageName *string `json:"packageName,omitempty"`
	Timestamp *int32 `json:"timestamp,omitempty"`
}

// NewEmaopayMonitorMessageParams instantiates a new EmaopayMonitorMessageParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmaopayMonitorMessageParams() *EmaopayMonitorMessageParams {
	this := EmaopayMonitorMessageParams{}
	return &this
}

// NewEmaopayMonitorMessageParamsWithDefaults instantiates a new EmaopayMonitorMessageParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmaopayMonitorMessageParamsWithDefaults() *EmaopayMonitorMessageParams {
	this := EmaopayMonitorMessageParams{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *EmaopayMonitorMessageParams) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayMonitorMessageParams) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *EmaopayMonitorMessageParams) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *EmaopayMonitorMessageParams) SetContent(v string) {
	o.Content = &v
}

// GetPackageName returns the PackageName field value if set, zero value otherwise.
func (o *EmaopayMonitorMessageParams) GetPackageName() string {
	if o == nil || IsNil(o.PackageName) {
		var ret string
		return ret
	}
	return *o.PackageName
}

// GetPackageNameOk returns a tuple with the PackageName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayMonitorMessageParams) GetPackageNameOk() (*string, bool) {
	if o == nil || IsNil(o.PackageName) {
		return nil, false
	}
	return o.PackageName, true
}

// HasPackageName returns a boolean if a field has been set.
func (o *EmaopayMonitorMessageParams) HasPackageName() bool {
	if o != nil && !IsNil(o.PackageName) {
		return true
	}

	return false
}

// SetPackageName gets a reference to the given string and assigns it to the PackageName field.
func (o *EmaopayMonitorMessageParams) SetPackageName(v string) {
	o.PackageName = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *EmaopayMonitorMessageParams) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int32
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayMonitorMessageParams) GetTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *EmaopayMonitorMessageParams) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int32 and assigns it to the Timestamp field.
func (o *EmaopayMonitorMessageParams) SetTimestamp(v int32) {
	o.Timestamp = &v
}

func (o EmaopayMonitorMessageParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmaopayMonitorMessageParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.PackageName) {
		toSerialize["packageName"] = o.PackageName
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

type NullableEmaopayMonitorMessageParams struct {
	value *EmaopayMonitorMessageParams
	isSet bool
}

func (v NullableEmaopayMonitorMessageParams) Get() *EmaopayMonitorMessageParams {
	return v.value
}

func (v *NullableEmaopayMonitorMessageParams) Set(val *EmaopayMonitorMessageParams) {
	v.value = val
	v.isSet = true
}

func (v NullableEmaopayMonitorMessageParams) IsSet() bool {
	return v.isSet
}

func (v *NullableEmaopayMonitorMessageParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmaopayMonitorMessageParams(val *EmaopayMonitorMessageParams) *NullableEmaopayMonitorMessageParams {
	return &NullableEmaopayMonitorMessageParams{value: val, isSet: true}
}

func (v NullableEmaopayMonitorMessageParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmaopayMonitorMessageParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


