/*
EmaoPay API

EmaoPay API.

API version: 1.0
Contact: support@emaopay.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emaopay

import (
	"encoding/json"
)

// checks if the EmaopayPagedResponseEmaopayOrder type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmaopayPagedResponseEmaopayOrder{}

// EmaopayPagedResponseEmaopayOrder struct for EmaopayPagedResponseEmaopayOrder
type EmaopayPagedResponseEmaopayOrder struct {
	Data []EmaopayOrder `json:"data,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewEmaopayPagedResponseEmaopayOrder instantiates a new EmaopayPagedResponseEmaopayOrder object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmaopayPagedResponseEmaopayOrder() *EmaopayPagedResponseEmaopayOrder {
	this := EmaopayPagedResponseEmaopayOrder{}
	return &this
}

// NewEmaopayPagedResponseEmaopayOrderWithDefaults instantiates a new EmaopayPagedResponseEmaopayOrder object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmaopayPagedResponseEmaopayOrderWithDefaults() *EmaopayPagedResponseEmaopayOrder {
	this := EmaopayPagedResponseEmaopayOrder{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EmaopayPagedResponseEmaopayOrder) GetData() []EmaopayOrder {
	if o == nil || IsNil(o.Data) {
		var ret []EmaopayOrder
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayPagedResponseEmaopayOrder) GetDataOk() ([]EmaopayOrder, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EmaopayPagedResponseEmaopayOrder) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []EmaopayOrder and assigns it to the Data field.
func (o *EmaopayPagedResponseEmaopayOrder) SetData(v []EmaopayOrder) {
	o.Data = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *EmaopayPagedResponseEmaopayOrder) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayPagedResponseEmaopayOrder) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *EmaopayPagedResponseEmaopayOrder) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *EmaopayPagedResponseEmaopayOrder) SetTotal(v int32) {
	o.Total = &v
}

func (o EmaopayPagedResponseEmaopayOrder) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmaopayPagedResponseEmaopayOrder) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableEmaopayPagedResponseEmaopayOrder struct {
	value *EmaopayPagedResponseEmaopayOrder
	isSet bool
}

func (v NullableEmaopayPagedResponseEmaopayOrder) Get() *EmaopayPagedResponseEmaopayOrder {
	return v.value
}

func (v *NullableEmaopayPagedResponseEmaopayOrder) Set(val *EmaopayPagedResponseEmaopayOrder) {
	v.value = val
	v.isSet = true
}

func (v NullableEmaopayPagedResponseEmaopayOrder) IsSet() bool {
	return v.isSet
}

func (v *NullableEmaopayPagedResponseEmaopayOrder) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmaopayPagedResponseEmaopayOrder(val *EmaopayPagedResponseEmaopayOrder) *NullableEmaopayPagedResponseEmaopayOrder {
	return &NullableEmaopayPagedResponseEmaopayOrder{value: val, isSet: true}
}

func (v NullableEmaopayPagedResponseEmaopayOrder) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmaopayPagedResponseEmaopayOrder) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


