/*
EmaoPay API

EmaoPay API.

API version: 1.0
Contact: support@emaopay.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emaopay

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmaopayCreateNewMonitorParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmaopayCreateNewMonitorParams{}

// EmaopayCreateNewMonitorParams struct for EmaopayCreateNewMonitorParams
type EmaopayCreateNewMonitorParams struct {
	MerchantId string `json:"merchantId"`
}

type _EmaopayCreateNewMonitorParams EmaopayCreateNewMonitorParams

// NewEmaopayCreateNewMonitorParams instantiates a new EmaopayCreateNewMonitorParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmaopayCreateNewMonitorParams(merchantId string) *EmaopayCreateNewMonitorParams {
	this := EmaopayCreateNewMonitorParams{}
	this.MerchantId = merchantId
	return &this
}

// NewEmaopayCreateNewMonitorParamsWithDefaults instantiates a new EmaopayCreateNewMonitorParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmaopayCreateNewMonitorParamsWithDefaults() *EmaopayCreateNewMonitorParams {
	this := EmaopayCreateNewMonitorParams{}
	return &this
}

// GetMerchantId returns the MerchantId field value
func (o *EmaopayCreateNewMonitorParams) GetMerchantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MerchantId
}

// GetMerchantIdOk returns a tuple with the MerchantId field value
// and a boolean to check if the value has been set.
func (o *EmaopayCreateNewMonitorParams) GetMerchantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MerchantId, true
}

// SetMerchantId sets field value
func (o *EmaopayCreateNewMonitorParams) SetMerchantId(v string) {
	o.MerchantId = v
}

func (o EmaopayCreateNewMonitorParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmaopayCreateNewMonitorParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["merchantId"] = o.MerchantId
	return toSerialize, nil
}

func (o *EmaopayCreateNewMonitorParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"merchantId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmaopayCreateNewMonitorParams := _EmaopayCreateNewMonitorParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmaopayCreateNewMonitorParams)

	if err != nil {
		return err
	}

	*o = EmaopayCreateNewMonitorParams(varEmaopayCreateNewMonitorParams)

	return err
}

type NullableEmaopayCreateNewMonitorParams struct {
	value *EmaopayCreateNewMonitorParams
	isSet bool
}

func (v NullableEmaopayCreateNewMonitorParams) Get() *EmaopayCreateNewMonitorParams {
	return v.value
}

func (v *NullableEmaopayCreateNewMonitorParams) Set(val *EmaopayCreateNewMonitorParams) {
	v.value = val
	v.isSet = true
}

func (v NullableEmaopayCreateNewMonitorParams) IsSet() bool {
	return v.isSet
}

func (v *NullableEmaopayCreateNewMonitorParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmaopayCreateNewMonitorParams(val *EmaopayCreateNewMonitorParams) *NullableEmaopayCreateNewMonitorParams {
	return &NullableEmaopayCreateNewMonitorParams{value: val, isSet: true}
}

func (v NullableEmaopayCreateNewMonitorParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmaopayCreateNewMonitorParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


