/*
EmaoPay API

EmaoPay API.

API version: 1.0
Contact: support@emaopay.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emaopaysdk

import (
	"encoding/json"
)

// checks if the EmaopayRegisterParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmaopayRegisterParams{}

// EmaopayRegisterParams struct for EmaopayRegisterParams
type EmaopayRegisterParams struct {
	Password *string `json:"password,omitempty"`
	Username *string `json:"username,omitempty"`
}

// NewEmaopayRegisterParams instantiates a new EmaopayRegisterParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmaopayRegisterParams() *EmaopayRegisterParams {
	this := EmaopayRegisterParams{}
	return &this
}

// NewEmaopayRegisterParamsWithDefaults instantiates a new EmaopayRegisterParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmaopayRegisterParamsWithDefaults() *EmaopayRegisterParams {
	this := EmaopayRegisterParams{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *EmaopayRegisterParams) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayRegisterParams) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *EmaopayRegisterParams) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *EmaopayRegisterParams) SetPassword(v string) {
	o.Password = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *EmaopayRegisterParams) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayRegisterParams) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *EmaopayRegisterParams) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *EmaopayRegisterParams) SetUsername(v string) {
	o.Username = &v
}

func (o EmaopayRegisterParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmaopayRegisterParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableEmaopayRegisterParams struct {
	value *EmaopayRegisterParams
	isSet bool
}

func (v NullableEmaopayRegisterParams) Get() *EmaopayRegisterParams {
	return v.value
}

func (v *NullableEmaopayRegisterParams) Set(val *EmaopayRegisterParams) {
	v.value = val
	v.isSet = true
}

func (v NullableEmaopayRegisterParams) IsSet() bool {
	return v.isSet
}

func (v *NullableEmaopayRegisterParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmaopayRegisterParams(val *EmaopayRegisterParams) *NullableEmaopayRegisterParams {
	return &NullableEmaopayRegisterParams{value: val, isSet: true}
}

func (v NullableEmaopayRegisterParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmaopayRegisterParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


