/*
EmaoPay API

EmaoPay API.

API version: 1.0
Contact: support@emaopay.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emaopaysdk

import (
	"encoding/json"
)

// checks if the EmaopayMonitorMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmaopayMonitorMessage{}

// EmaopayMonitorMessage struct for EmaopayMonitorMessage
type EmaopayMonitorMessage struct {
	Content *string `json:"content,omitempty"`
	Handled *bool `json:"handled,omitempty"`
	MonitorId *string `json:"monitorId,omitempty"`
	PackageName *string `json:"packageName,omitempty"`
	Timestamp *int32 `json:"timestamp,omitempty"`
}

// NewEmaopayMonitorMessage instantiates a new EmaopayMonitorMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmaopayMonitorMessage() *EmaopayMonitorMessage {
	this := EmaopayMonitorMessage{}
	return &this
}

// NewEmaopayMonitorMessageWithDefaults instantiates a new EmaopayMonitorMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmaopayMonitorMessageWithDefaults() *EmaopayMonitorMessage {
	this := EmaopayMonitorMessage{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *EmaopayMonitorMessage) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayMonitorMessage) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *EmaopayMonitorMessage) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *EmaopayMonitorMessage) SetContent(v string) {
	o.Content = &v
}

// GetHandled returns the Handled field value if set, zero value otherwise.
func (o *EmaopayMonitorMessage) GetHandled() bool {
	if o == nil || IsNil(o.Handled) {
		var ret bool
		return ret
	}
	return *o.Handled
}

// GetHandledOk returns a tuple with the Handled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayMonitorMessage) GetHandledOk() (*bool, bool) {
	if o == nil || IsNil(o.Handled) {
		return nil, false
	}
	return o.Handled, true
}

// HasHandled returns a boolean if a field has been set.
func (o *EmaopayMonitorMessage) HasHandled() bool {
	if o != nil && !IsNil(o.Handled) {
		return true
	}

	return false
}

// SetHandled gets a reference to the given bool and assigns it to the Handled field.
func (o *EmaopayMonitorMessage) SetHandled(v bool) {
	o.Handled = &v
}

// GetMonitorId returns the MonitorId field value if set, zero value otherwise.
func (o *EmaopayMonitorMessage) GetMonitorId() string {
	if o == nil || IsNil(o.MonitorId) {
		var ret string
		return ret
	}
	return *o.MonitorId
}

// GetMonitorIdOk returns a tuple with the MonitorId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayMonitorMessage) GetMonitorIdOk() (*string, bool) {
	if o == nil || IsNil(o.MonitorId) {
		return nil, false
	}
	return o.MonitorId, true
}

// HasMonitorId returns a boolean if a field has been set.
func (o *EmaopayMonitorMessage) HasMonitorId() bool {
	if o != nil && !IsNil(o.MonitorId) {
		return true
	}

	return false
}

// SetMonitorId gets a reference to the given string and assigns it to the MonitorId field.
func (o *EmaopayMonitorMessage) SetMonitorId(v string) {
	o.MonitorId = &v
}

// GetPackageName returns the PackageName field value if set, zero value otherwise.
func (o *EmaopayMonitorMessage) GetPackageName() string {
	if o == nil || IsNil(o.PackageName) {
		var ret string
		return ret
	}
	return *o.PackageName
}

// GetPackageNameOk returns a tuple with the PackageName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayMonitorMessage) GetPackageNameOk() (*string, bool) {
	if o == nil || IsNil(o.PackageName) {
		return nil, false
	}
	return o.PackageName, true
}

// HasPackageName returns a boolean if a field has been set.
func (o *EmaopayMonitorMessage) HasPackageName() bool {
	if o != nil && !IsNil(o.PackageName) {
		return true
	}

	return false
}

// SetPackageName gets a reference to the given string and assigns it to the PackageName field.
func (o *EmaopayMonitorMessage) SetPackageName(v string) {
	o.PackageName = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *EmaopayMonitorMessage) GetTimestamp() int32 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int32
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayMonitorMessage) GetTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *EmaopayMonitorMessage) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int32 and assigns it to the Timestamp field.
func (o *EmaopayMonitorMessage) SetTimestamp(v int32) {
	o.Timestamp = &v
}

func (o EmaopayMonitorMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmaopayMonitorMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	if !IsNil(o.Handled) {
		toSerialize["handled"] = o.Handled
	}
	if !IsNil(o.MonitorId) {
		toSerialize["monitorId"] = o.MonitorId
	}
	if !IsNil(o.PackageName) {
		toSerialize["packageName"] = o.PackageName
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

type NullableEmaopayMonitorMessage struct {
	value *EmaopayMonitorMessage
	isSet bool
}

func (v NullableEmaopayMonitorMessage) Get() *EmaopayMonitorMessage {
	return v.value
}

func (v *NullableEmaopayMonitorMessage) Set(val *EmaopayMonitorMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableEmaopayMonitorMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableEmaopayMonitorMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmaopayMonitorMessage(val *EmaopayMonitorMessage) *NullableEmaopayMonitorMessage {
	return &NullableEmaopayMonitorMessage{value: val, isSet: true}
}

func (v NullableEmaopayMonitorMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmaopayMonitorMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


