/*
EmaoPay API

EmaoPay API.

API version: 1.0
Contact: support@emaopay.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emaopaysdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmaopayCreateMerchantParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmaopayCreateMerchantParams{}

// EmaopayCreateMerchantParams struct for EmaopayCreateMerchantParams
type EmaopayCreateMerchantParams struct {
	Name string `json:"name"`
}

type _EmaopayCreateMerchantParams EmaopayCreateMerchantParams

// NewEmaopayCreateMerchantParams instantiates a new EmaopayCreateMerchantParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmaopayCreateMerchantParams(name string) *EmaopayCreateMerchantParams {
	this := EmaopayCreateMerchantParams{}
	this.Name = name
	return &this
}

// NewEmaopayCreateMerchantParamsWithDefaults instantiates a new EmaopayCreateMerchantParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmaopayCreateMerchantParamsWithDefaults() *EmaopayCreateMerchantParams {
	this := EmaopayCreateMerchantParams{}
	return &this
}

// GetName returns the Name field value
func (o *EmaopayCreateMerchantParams) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EmaopayCreateMerchantParams) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EmaopayCreateMerchantParams) SetName(v string) {
	o.Name = v
}

func (o EmaopayCreateMerchantParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmaopayCreateMerchantParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *EmaopayCreateMerchantParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmaopayCreateMerchantParams := _EmaopayCreateMerchantParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmaopayCreateMerchantParams)

	if err != nil {
		return err
	}

	*o = EmaopayCreateMerchantParams(varEmaopayCreateMerchantParams)

	return err
}

type NullableEmaopayCreateMerchantParams struct {
	value *EmaopayCreateMerchantParams
	isSet bool
}

func (v NullableEmaopayCreateMerchantParams) Get() *EmaopayCreateMerchantParams {
	return v.value
}

func (v *NullableEmaopayCreateMerchantParams) Set(val *EmaopayCreateMerchantParams) {
	v.value = val
	v.isSet = true
}

func (v NullableEmaopayCreateMerchantParams) IsSet() bool {
	return v.isSet
}

func (v *NullableEmaopayCreateMerchantParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmaopayCreateMerchantParams(val *EmaopayCreateMerchantParams) *NullableEmaopayCreateMerchantParams {
	return &NullableEmaopayCreateMerchantParams{value: val, isSet: true}
}

func (v NullableEmaopayCreateMerchantParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmaopayCreateMerchantParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


