/*
EmaoPay API

EmaoPay API.

API version: 1.0
Contact: support@emaopay.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emaopaysdk

import (
	"encoding/json"
)

// checks if the EmaopayDeleteQrCodeParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmaopayDeleteQrCodeParams{}

// EmaopayDeleteQrCodeParams struct for EmaopayDeleteQrCodeParams
type EmaopayDeleteQrCodeParams struct {
	Ids []string `json:"ids,omitempty"`
}

// NewEmaopayDeleteQrCodeParams instantiates a new EmaopayDeleteQrCodeParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmaopayDeleteQrCodeParams() *EmaopayDeleteQrCodeParams {
	this := EmaopayDeleteQrCodeParams{}
	return &this
}

// NewEmaopayDeleteQrCodeParamsWithDefaults instantiates a new EmaopayDeleteQrCodeParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmaopayDeleteQrCodeParamsWithDefaults() *EmaopayDeleteQrCodeParams {
	this := EmaopayDeleteQrCodeParams{}
	return &this
}

// GetIds returns the Ids field value if set, zero value otherwise.
func (o *EmaopayDeleteQrCodeParams) GetIds() []string {
	if o == nil || IsNil(o.Ids) {
		var ret []string
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayDeleteQrCodeParams) GetIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *EmaopayDeleteQrCodeParams) HasIds() bool {
	if o != nil && !IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []string and assigns it to the Ids field.
func (o *EmaopayDeleteQrCodeParams) SetIds(v []string) {
	o.Ids = v
}

func (o EmaopayDeleteQrCodeParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmaopayDeleteQrCodeParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ids) {
		toSerialize["ids"] = o.Ids
	}
	return toSerialize, nil
}

type NullableEmaopayDeleteQrCodeParams struct {
	value *EmaopayDeleteQrCodeParams
	isSet bool
}

func (v NullableEmaopayDeleteQrCodeParams) Get() *EmaopayDeleteQrCodeParams {
	return v.value
}

func (v *NullableEmaopayDeleteQrCodeParams) Set(val *EmaopayDeleteQrCodeParams) {
	v.value = val
	v.isSet = true
}

func (v NullableEmaopayDeleteQrCodeParams) IsSet() bool {
	return v.isSet
}

func (v *NullableEmaopayDeleteQrCodeParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmaopayDeleteQrCodeParams(val *EmaopayDeleteQrCodeParams) *NullableEmaopayDeleteQrCodeParams {
	return &NullableEmaopayDeleteQrCodeParams{value: val, isSet: true}
}

func (v NullableEmaopayDeleteQrCodeParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmaopayDeleteQrCodeParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


