/*
EmaoPay API

EmaoPay API.

API version: 1.0
Contact: support@emaopay.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emaopaysdk

import (
	"encoding/json"
)

// checks if the EmaopayLoginResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmaopayLoginResponse{}

// EmaopayLoginResponse struct for EmaopayLoginResponse
type EmaopayLoginResponse struct {
	Token *string `json:"token,omitempty"`
}

// NewEmaopayLoginResponse instantiates a new EmaopayLoginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmaopayLoginResponse() *EmaopayLoginResponse {
	this := EmaopayLoginResponse{}
	return &this
}

// NewEmaopayLoginResponseWithDefaults instantiates a new EmaopayLoginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmaopayLoginResponseWithDefaults() *EmaopayLoginResponse {
	this := EmaopayLoginResponse{}
	return &this
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *EmaopayLoginResponse) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayLoginResponse) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *EmaopayLoginResponse) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *EmaopayLoginResponse) SetToken(v string) {
	o.Token = &v
}

func (o EmaopayLoginResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmaopayLoginResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	return toSerialize, nil
}

type NullableEmaopayLoginResponse struct {
	value *EmaopayLoginResponse
	isSet bool
}

func (v NullableEmaopayLoginResponse) Get() *EmaopayLoginResponse {
	return v.value
}

func (v *NullableEmaopayLoginResponse) Set(val *EmaopayLoginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmaopayLoginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmaopayLoginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmaopayLoginResponse(val *EmaopayLoginResponse) *NullableEmaopayLoginResponse {
	return &NullableEmaopayLoginResponse{value: val, isSet: true}
}

func (v NullableEmaopayLoginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmaopayLoginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


