/*
EmaoPay API

EmaoPay API.

API version: 1.0
Contact: support@emaopay.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emaopaysdk

import (
	"encoding/json"
)

// checks if the EmaopayPagedResponseEmaopayMonitorMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmaopayPagedResponseEmaopayMonitorMessage{}

// EmaopayPagedResponseEmaopayMonitorMessage struct for EmaopayPagedResponseEmaopayMonitorMessage
type EmaopayPagedResponseEmaopayMonitorMessage struct {
	Data []EmaopayMonitorMessage `json:"data,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewEmaopayPagedResponseEmaopayMonitorMessage instantiates a new EmaopayPagedResponseEmaopayMonitorMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmaopayPagedResponseEmaopayMonitorMessage() *EmaopayPagedResponseEmaopayMonitorMessage {
	this := EmaopayPagedResponseEmaopayMonitorMessage{}
	return &this
}

// NewEmaopayPagedResponseEmaopayMonitorMessageWithDefaults instantiates a new EmaopayPagedResponseEmaopayMonitorMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmaopayPagedResponseEmaopayMonitorMessageWithDefaults() *EmaopayPagedResponseEmaopayMonitorMessage {
	this := EmaopayPagedResponseEmaopayMonitorMessage{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EmaopayPagedResponseEmaopayMonitorMessage) GetData() []EmaopayMonitorMessage {
	if o == nil || IsNil(o.Data) {
		var ret []EmaopayMonitorMessage
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayPagedResponseEmaopayMonitorMessage) GetDataOk() ([]EmaopayMonitorMessage, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EmaopayPagedResponseEmaopayMonitorMessage) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []EmaopayMonitorMessage and assigns it to the Data field.
func (o *EmaopayPagedResponseEmaopayMonitorMessage) SetData(v []EmaopayMonitorMessage) {
	o.Data = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *EmaopayPagedResponseEmaopayMonitorMessage) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmaopayPagedResponseEmaopayMonitorMessage) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *EmaopayPagedResponseEmaopayMonitorMessage) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *EmaopayPagedResponseEmaopayMonitorMessage) SetTotal(v int32) {
	o.Total = &v
}

func (o EmaopayPagedResponseEmaopayMonitorMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmaopayPagedResponseEmaopayMonitorMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableEmaopayPagedResponseEmaopayMonitorMessage struct {
	value *EmaopayPagedResponseEmaopayMonitorMessage
	isSet bool
}

func (v NullableEmaopayPagedResponseEmaopayMonitorMessage) Get() *EmaopayPagedResponseEmaopayMonitorMessage {
	return v.value
}

func (v *NullableEmaopayPagedResponseEmaopayMonitorMessage) Set(val *EmaopayPagedResponseEmaopayMonitorMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableEmaopayPagedResponseEmaopayMonitorMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableEmaopayPagedResponseEmaopayMonitorMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmaopayPagedResponseEmaopayMonitorMessage(val *EmaopayPagedResponseEmaopayMonitorMessage) *NullableEmaopayPagedResponseEmaopayMonitorMessage {
	return &NullableEmaopayPagedResponseEmaopayMonitorMessage{value: val, isSet: true}
}

func (v NullableEmaopayPagedResponseEmaopayMonitorMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmaopayPagedResponseEmaopayMonitorMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


